// <auto-generated />
using System;
using CoffeeMachine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeMachine.Data.Migrations
{
    [DbContext(typeof(CoffeeMachineContext))]
    [Migration("20250331193417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeMachine.Models.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("CoffeeMachine.Models.Entities.ActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabledAction")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ActionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Turn off",
                            Description = "Turn off the machine if idle, no coffe will be surved !",
                            IsDisabledAction = false
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Turn On",
                            Description = "Turing On the machine if off",
                            IsDisabledAction = false
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "Make Coffee",
                            Description = "making coffe if idle (On, not making coffe and no alert)",
                            IsDisabledAction = false
                        });
                });

            modelBuilder.Entity("CoffeeMachine.Models.Entities.CoffeeActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CoffeeCreationOptionsId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("CoffeeCreationOptionsId");

                    b.ToTable("CoffeeActionLogs");
                });

            modelBuilder.Entity("CoffeeMachine.Models.Entities.CoffeeCreationOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AddMilk")
                        .HasColumnType("bit");

                    b.Property<int?>("NumEspressoShots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoffeeCreationOptions");
                });

            modelBuilder.Entity("CoffeeMachine.Models.Entities.CoffeeMachineState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeanFeed")
                        .HasColumnType("int");

                    b.Property<bool>("IsMakingCoffee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<int>("WasteCoffee")
                        .HasColumnType("int");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("int");

                    b.Property<int>("WaterTray")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoffeeMachineStates");
                });

            modelBuilder.Entity("CoffeeMachine.Models.Entities.CoffeeActionLog", b =>
                {
                    b.HasOne("CoffeeMachine.Models.Entities.Action", "Action")
                        .WithMany("CoffeeActionLogs")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeMachine.Models.Entities.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeMachine.Models.Entities.CoffeeCreationOptions", "CoffeeCreationOptions")
                        .WithMany()
                        .HasForeignKey("CoffeeCreationOptionsId");

                    b.Navigation("Action");

                    b.Navigation("ActionType");

                    b.Navigation("CoffeeCreationOptions");
                });

            modelBuilder.Entity("CoffeeMachine.Models.Entities.Action", b =>
                {
                    b.Navigation("CoffeeActionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
